#scanner1
/gate/world/daughters/name                    scanner1
/gate/world/daughters/systemType	      scanner
/gate/world/daughters/insert                  cylinder
/gate/scanner1/placement/setTranslation 0.0 0.0 0.0 cm
/gate/scanner1/placement/alignToY
/gate/scanner1/geometry/setPhiStart -90. deg
/gate/scanner1/geometry/setDeltaPhi 180. deg
/gate/scanner1/geometry/setRmax         70.0 mm 

# cristals are separated by 57.7mm, so the radius is 28.85mm, and they have 20mm length. 
#Considering the rotations, at least 55mm for exteral radius is needed 

/gate/scanner1/geometry/setRmin         25.0 mm 

#minimum distance between cristals is 57.7mm, so 23*2mm=46mm has a safety tolerance. 

/gate/scanner1/geometry/setHeight       75 mm 
/gate/scanner1/setMaterial              Air
/gate/scanner1/vis/forceWireframe
/gate/scanner1/vis/setColor             white

#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#	HEAD
/gate/scanner1/daughters/name           head
/gate/scanner1/daughters/insert         box
/gate/head/placement/setTranslation           45.0 0.0 0.0 mm
/gate/head/geometry/setXLength                30.  mm
/gate/head/geometry/setYLength                20.0 mm 
#4.91 mm
/gate/head/geometry/setZLength                73.24 mm
/gate/head/setMaterial                        Air
/gate/head/vis/setVisible                     1





#	BLOCK
#	BLOCK
/gate/head/daughters/name                     block
/gate/head/daughters/insert                   box
/gate/block/geometry/setXLength               30. mm
/gate/block/geometry/setYLength               4.91 mm
/gate/block/geometry/setZLength               73.24 mm
/gate/block/setMaterial                       Air
/gate/block/vis/setVisible                    1

#	C R Y S T A L
/gate/block/daughters/name                    crystal
/gate/block/daughters/insert                  box
#/gate/crystal/placement/setTranslation        0.0 0.175 0.14 mm
/gate/crystal/geometry/setXLength             30 mm
/gate/crystal/geometry/setYLength             2.0 mm
/gate/crystal/geometry/setZLength             2.0 mm
/gate/crystal/setMaterial                     Air
/gate/crystal/vis/setVisible                  1
/gate/crystal/vis/setColor                        cyan

/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 1
/gate/crystal/cubicArray/setRepeatNumberY 2
/gate/crystal/cubicArray/setRepeatNumberZ 16
/gate/crystal/cubicArray/setRepeatVector 0. 2.35 2.28 mm



#	A T T A C H    S Y S T E M 
/gate/systems/scanner1/level1/attach   head
/gate/systems/scanner1/level2/attach   block
/gate/systems/scanner1/level3/attach   crystal



#	A T T A C H    C R Y S T A L  SD

#/gate/crystal/attachCrystalSD

# SOURCE
/gate/head/daughters/name source_enclosure
/gate/head/daughters/insert box
/gate/source_enclosure/geometry/setXLength 27.4 mm
/gate/source_enclosure/geometry/setYLength 6 mm
/gate/source_enclosure/geometry/setZLength 27.4 mm
/gate/source_enclosure/setMaterial Air
/gate/source_enclosure/placement/setTranslation -2.45 7.70 0. mm
/gate/source_enclosure/placement/setRotationAxis 0 0 1
/gate/source_enclosure/placement/setRotationAngle 11.6 deg

/gate/source_enclosure/daughters/name source_enclosure1
/gate/source_enclosure/daughters/insert cylinder
/gate/source_enclosure1/geometry/setRmin 0. mm
/gate/source_enclosure1/geometry/setRmax 13.7 mm
/gate/source_enclosure1/geometry/setHeight 6. mm
#/gate/source_enclosure1/placement/setTranslation -2.45 5.35 0. mm
/gate/source_enclosure1/placement/alignToY
/gate/source_enclosure1/setMaterial Air
/gate/source_enclosure1/vis/setVisible 1
/gate/source_enclosure1/vis/setColor white

/gate/source_enclosure1/daughters/name disk_enclosure
/gate/source_enclosure1/daughters/insert cylinder
/gate/disk_enclosure/geometry/setRmin 12.7 mm
/gate/disk_enclosure/geometry/setRmax 13.7 mm
/gate/disk_enclosure/geometry/setHeight 6. mm
/gate/disk_enclosure/geometry/setPhiStart 215 deg
/gate/disk_enclosure/geometry/setDeltaPhi 290 deg
/gate/disk_enclosure/setMaterial Lead
/gate/disk_enclosure/vis/setVisible 1
/gate/disk_enclosure/vis/forceSolid
/gate/disk_enclosure/vis/setColor gray

/gate/source_enclosure1/daughters/name disk_cover1
/gate/source_enclosure1/daughters/insert cylinder
/gate/disk_cover1/geometry/setRmin 0 mm
/gate/disk_cover1/geometry/setRmax 12.7 mm
/gate/disk_cover1/geometry/setHeight 1 mm
/gate/disk_cover1/setMaterial Lead
/gate/disk_cover1/placement/setTranslation 0 0 -2.5 mm
/gate/disk_cover1/vis/setVisible 1
/gate/disk_cover1/vis/forceSolid
/gate/disk_cover1/vis/setColor gray

/gate/source_enclosure1/daughters/name disk_cover2
/gate/source_enclosure1/daughters/insert cylinder
/gate/disk_cover2/geometry/setRmin 0 mm
/gate/disk_cover2/geometry/setRmax 12.7 mm
/gate/disk_cover2/geometry/setHeight 1 mm
/gate/disk_cover2/setMaterial Lead
/gate/disk_cover2/placement/setTranslation 0 0 2.5 mm
/gate/disk_cover2/vis/setVisible 1
/gate/disk_cover2/vis/forceSolid
/gate/disk_cover2/vis/setColor gray

/gate/source_enclosure1/daughters/name disk
/gate/source_enclosure1/daughters/insert cylinder
/gate/disk/geometry/setRmin 0 mm
/gate/disk/geometry/setRmax 12.7 mm			
/gate/disk/geometry/setHeight 4 mm
/gate/disk/setMaterial PMMA
/gate/disk/vis/setVisible 1
/gate/disk_cover2/vis/forceSolid
/gate/disk/vis/setColor red

