__version__ = "2025.1"
__author__ = "Pedro Encarnação"
__email__ = "pedro.encarnacao@ua.pt"
__license__ = "CC BY-NC-SA 4.0"
__status__ = "Development"
__date__ = "2025-01-08"
__maintainer__ = "Pedro Encarnação"
__credits__ = ["P. M. C. C. Encarnação"]
__description__ = ""
